version: '2'
services:
  web:
    build: .
    ports:
    - "3000:3000"
    expose:
    - "3000"
    links:
    - db
    env_file:
    - ./app.env
    volumes:
    - .:/app
  db:
    image: mongo
    ports:
        - "27017:27017"
    expose:
        - "27017"
#  db_backup:
#    image: tutum/mongodb-backup
#    links:
#    - db
#    volumes:
#    - /data/db:/backup
